(()=>{
const V3KEY='ceaMetroV3';
const TAGS=['Formule','Calcul','Lecture','Vocabulaire','Piège','Concept'];
const SUBJECTS=['Finance','Stats','Non-vie','Vie'];
const now=()=>Date.now();
const dayKey=()=>new Date().toISOString().slice(0,10);
let v3;try{v3=JSON.parse(localStorage.getItem(V3KEY)||'{}')}catch(e){v3={}}
v3.q=v3.q||{};v3.tags=v3.tags||{};v3.sessions=v3.sessions||[];v3.mission=v3.mission||{};
if(v3.mission.date!==dayKey())v3.mission={date:dayKey(),adaptive:false,traps:false,minute:false};
let currentMode='custom',questionStarted=now(),examState=null;
function persist(){localStorage.setItem(V3KEY,JSON.stringify(v3));renderV3()}
function qs(id){if(!v3.q[id])v3.q[id]={a:0,c:0,streak:0,last:0,due:0,time:0,tags:{}};return v3.q[id]}
function record(x,ok,ms){const s=qs(x.id);s.a++;if(ok){s.c++;s.streak++;const hours=[6,12,24,48,96,144][Math.min(s.streak-1,5)];s.due=now()+hours*3600000}else{s.streak=0;s.due=now()+3*3600000}s.last=now();s.time+=Math.min(ms||0,300000)}
function priority(x){const s=qs(x.id),err=s.a?1-s.c/s.a:.45,legacy=(state.weak[x.id]||0)*.32,freq=1+.18*(x.years.length-1),trap=x.trap?1.15:1,age=s.last?Math.min(2,(now()-s.last)/(12*3600000))+.15:1.2,due=!s.due||s.due<=now()?1.5:.35;return (0.65+err*1.8+legacy)*freq*trap*age*due}
function adaptiveIds(n,filter=null){let cand=Q.filter(x=>!filter||filter(x)).map(x=>({x,p:priority(x)*(0.88+Math.random()*.24)})).sort((a,b)=>b.p-a.p),out=[],per={};for(const o of cand){const k=o.x.s+'|'+o.x.t,limit=n<=5?1:2;if((per[k]||0)>=limit)continue;out.push(o.x.id);per[k]=(per[k]||0)+1;if(out.length>=n)break}if(out.length<n){for(const o of cand){if(!out.includes(o.x.id))out.push(o.x.id);if(out.length>=n)break}}return out}
function oneMinuteIds(){const calcTopics=['CRD','In fine','Coût du crédit','Chain-Ladder','PPNA','Prime acquise','Table de mortalité','Survie','Décès'];const trap=adaptiveIds(1,x=>!!x.trap);const calc=adaptiveIds(1,x=>calcTopics.includes(x.t)&&!trap.includes(x.id));const concept=adaptiveIds(1,x=>!trap.includes(x.id)&&!calc.includes(x.id));return [...trap,...calc,...concept].slice(0,3)}
function trapIds(n=5){return adaptiveIds(n,x=>!!x.trap)}
function balancedExam(year=null){let ids=[];for(const s of SUBJECTS){let p=Q.filter(x=>x.s===s&&(!year||x.years.includes(year)));let chosen=shuffle(p.map(x=>x.id)).slice(0,14);if(chosen.length<14){let fill=shuffle(Q.filter(x=>x.s===s&&!chosen.includes(x.id)).map(x=>x.id)).slice(0,14-chosen.length);chosen=chosen.concat(fill)}ids=ids.concat(chosen)}return shuffle(ids)}
function launchAdaptive(n=12,mode='adaptive'){currentMode=mode;subject='Tous';sourceYear='Tous';renderFilters();setTab('train');start(adaptiveIds(n),n)}
function launchTraps(){currentMode='traps';setTab('train');start(trapIds(5),5)}
function launchMinute(){currentMode='minute';setTab('train');const ids=oneMinuteIds();start(ids,ids.length)}
function launchTopic(s,t){currentMode='topic';setTab('train');const pool=Q.filter(x=>x.s===s&&x.t===t).map(x=>x.id);const ids=pool.length>=3?shuffle(pool).slice(0,5):adaptiveIds(5,x=>x.s===s&&(x.t===t||Q.filter(y=>y.s===s&&y.t===t).length<3));start(ids,ids.length)}
const baseShow=showQ;showQ=function(){baseShow();questionStarted=now()};
const baseAnswer=answer;answer=function(btn,ok,x){record(x,ok,now()-questionStarted);baseAnswer(btn,ok,x);if(!ok)addMistakeTags(x);persist()};
function addMistakeTags(x){const fb=$('fb');const wrap=document.createElement('div');wrap.className='mistakeTags';wrap.innerHTML='<div class="label">Pourquoi cette erreur ?</div><div class="tagButtons"></div>';const holder=wrap.querySelector('.tagButtons');TAGS.forEach(tag=>{const b=document.createElement('button');b.className='tagbtn';b.textContent=tag;b.onclick=()=>{const s=qs(x.id);s.tags[tag]=(s.tags[tag]||0)+1;v3.tags[tag]=(v3.tags[tag]||0)+1;holder.querySelectorAll('button').forEach(z=>z.disabled=true);b.classList.add('picked');persist()};holder.appendChild(b)});fb.appendChild(wrap)}
const baseFinish=finish;finish=function(){const total=session.length,got=score,wrong=[...new Set(sessionWrong)];baseFinish();v3.sessions.unshift({date:now(),mode:currentMode,score:got,total,wrong});v3.sessions=v3.sessions.slice(0,20);if(currentMode==='adaptive'&&total>=10)v3.mission.adaptive=true;if(currentMode==='traps'&&total>=5)v3.mission.traps=true;if(currentMode==='minute')v3.mission.minute=true;persist()};
const baseSave=save;save=function(){baseSave();renderV3()};
function pct(c,a){return a?Math.round(100*c/a):null}
function subjectScore(s){const v=state.bySubject[s];return v&&v.a?pct(v.c,v.a):null}
function topicRows(){const map={};Q.forEach(x=>{const k=x.s+'|'+x.t;if(!map[k])map[k]={s:x.s,t:x.t,a:0,c:0,n:0,years:new Set()};const st=qs(x.id);map[k].a+=st.a;map[k].c+=st.c;map[k].n++;x.years.forEach(y=>map[k].years.add(y))});return Object.values(map).map(r=>({...r,p:r.a?pct(r.c,r.a):null,freq:r.years.size})).sort((a,b)=>a.s.localeCompare(b.s)||((a.p??-1)-(b.p??-1)))}
function recommended(){const ranked=Q.map(x=>({x,p:priority(x)})).sort((a,b)=>b.p-a.p);return ranked.length?ranked[0].x:null}
function metricScores(){let a=0,c=0,ta=0,tc=0;Object.entries(v3.q).forEach(([id,s])=>{a+=s.a;c+=s.c;const q=Q.find(x=>x.id===+id);if(q&&q.trap){ta+=s.a;tc+=s.c}});const avoid=(v3.tags.Calcul||0)+(v3.tags.Lecture||0)+(v3.tags.Vocabulaire||0)+(v3.tags['Piège']||0);return{knowledge:a?pct(c,a):(state.attempts?pct(state.correct,state.attempts):null),traps:ta?pct(tc,ta):null,technique:a?Math.max(0,Math.round(100*(1-avoid/a))):null}}
function renderHome(){const r=recommended(),m=metricScores();if($('recommendText'))$('recommendText').textContent=r?`${r.s} · ${r.t}`:'Commence par un diagnostic';if($('knowledgeScore'))$('knowledgeScore').textContent=m.knowledge==null?'—':m.knowledge+'%';if($('techScore'))$('techScore').textContent=m.technique==null?'—':m.technique+'%';if($('trapScore'))$('trapScore').textContent=m.traps==null?'—':m.traps+'%';if($('missionAdaptive'))$('missionAdaptive').classList.toggle('done',!!v3.mission.adaptive);if($('missionTraps'))$('missionTraps').classList.toggle('done',!!v3.mission.traps);if($('missionMinute'))$('missionMinute').classList.toggle('done',!!v3.mission.minute);const done=[v3.mission.adaptive,v3.mission.traps,v3.mission.minute].filter(Boolean).length;if($('missionProgress'))$('missionProgress').style.width=(done/3*100)+'%';if($('missionCount'))$('missionCount').textContent=`${done}/3`;renderRecent()}
function renderRecent(){const el=$('recentSessions');if(!el)return;el.innerHTML=v3.sessions.length?'':'<div class="empty">Aucune session V3 pour le moment.</div>';v3.sessions.slice(0,5).forEach(s=>{const d=document.createElement('div');d.className='recentRow';d.innerHTML=`<span>${new Date(s.date).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'})} · ${s.mode}</span><b>${s.score}/${s.total}</b>`;el.appendChild(d)})}
function renderMastery(){const root=$('masteryList');if(!root)return;root.innerHTML='';for(const s of SUBJECTS){const sec=document.createElement('div');sec.className='masterySubject';const sp=subjectScore(s);sec.innerHTML=`<div class="masteryHead"><b>${s}</b><span>${sp==null?'non testé':sp+'%'}</span></div>`;topicRows().filter(r=>r.s===s).forEach(r=>{const row=document.createElement('div');row.className='masteryRow';const p=r.p==null?0:r.p;row.innerHTML=`<button class="topicDrill"><span><b>${r.t}</b><small>${r.a?`${r.a} essais · ${r.freq}/3 annales`:'non testé · '+r.freq+'/3 annales'}</small></span><span>${r.p==null?'—':r.p+'%'}</span></button><div class="masteryBar"><i style="width:${p}%"></i></div>`;row.querySelector('button').onclick=()=>launchTopic(r.s,r.t);sec.appendChild(row)});root.appendChild(sec)}renderErrorProfile()}
function renderErrorProfile(){const el=$('errorProfile');if(!el)return;const arr=Object.entries(v3.tags).sort((a,b)=>b[1]-a[1]);el.innerHTML=arr.length?'':'<div class="mut">Tague tes erreurs après les QCM pour distinguer lacunes et erreurs évitables.</div>';arr.forEach(([k,v])=>{const d=document.createElement('div');d.className='errorTagRow';d.innerHTML=`<span>${k}</span><b>${v}</b>`;el.appendChild(d)})}
function renderV3(){renderHome();renderMastery()}
function augmentAnnales(){document.querySelectorAll('.yearcard').forEach(card=>{if(card.querySelector('.mockYear'))return;const y=+(card.querySelector('h3')?.textContent||0);if(!y)return;const b=document.createElement('button');b.className='secondary mockYear';b.textContent=`Simulation 56Q inspirée ${y}`;b.style.marginTop='8px';b.onclick=()=>startExam(y);card.appendChild(b)})}
const baseAnnales=renderAnnales;renderAnnales=function(){baseAnnales();augmentAnnales()};renderAnnales();
function startExam(year=null){currentMode=year?'annale-'+year:'mock';const ids=balancedExam(year);examState={ids,items:ids.map(id=>{const x=Q.find(q=>q.id===id);return{x,opts:shuffle(x.a.map((text,k)=>({text,k})))}}),answers:{},flags:{},idx:0,start:now(),end:now()+3*3600000,times:{},entered:now(),year,timer:null};setTab('mock');$('mockStart').classList.add('hidden');$('mockResult').classList.add('hidden');$('mockRun').classList.remove('hidden');renderExam();examState.timer=setInterval(updateTimer,1000);updateTimer()}
function leaveExam(){if(!examState)return;const id=examState.items[examState.idx].x.id;examState.times[id]=(examState.times[id]||0)+(now()-examState.entered);examState.entered=now()}
function renderExam(){if(!examState)return;const it=examState.items[examState.idx],x=it.x;$('mockCounter').textContent=`${examState.idx+1}/56`;$('mockTopic').textContent=`${x.s} · ${x.t}`;$('mockQuestion').textContent=x.q;$('mockAnswers').innerHTML='';it.opts.forEach(o=>{const b=document.createElement('button');b.className='ans';b.textContent=o.text;if(examState.answers[x.id]===o.k)b.classList.add('selectedAnswer');b.onclick=()=>{examState.answers[x.id]=o.k;renderExamGrid();renderExam()};$('mockAnswers').appendChild(b)});$('flagBtn').textContent=examState.flags[x.id]?'★ Signalée':'☆ Signaler';renderExamGrid()}
function renderExamGrid(){const g=$('examGrid');if(!g||!examState)return;g.innerHTML='';examState.items.forEach((it,i)=>{const b=document.createElement('button');b.className='gridQ';if(examState.answers[it.x.id]!=null)b.classList.add('answered');if(examState.flags[it.x.id])b.classList.add('flagged');if(i===examState.idx)b.classList.add('current');b.textContent=i+1;b.onclick=()=>{leaveExam();examState.idx=i;renderExam()};g.appendChild(b)});$('answeredCount').textContent=Object.keys(examState.answers).length}
function navExam(d){leaveExam();examState.idx=Math.max(0,Math.min(55,examState.idx+d));renderExam()}
function updateTimer(){if(!examState)return;let left=Math.max(0,examState.end-now()),h=Math.floor(left/3600000),m=Math.floor(left%3600000/60000),s=Math.floor(left%60000/1000);$('mockTimer').textContent=`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(left<=0)submitExam(true)}
function submitExam(auto=false){if(!examState)return;if(!auto&&!confirm('Terminer la simulation et afficher le score ?'))return;leaveExam();clearInterval(examState.timer);let total=56,correct=0,by={};const wrong=[];examState.items.forEach(it=>{const x=it.x,choice=examState.answers[x.id];by[x.s]=by[x.s]||{a:0,c:0};by[x.s].a++;if(choice===x.c){correct++;by[x.s].c++}else wrong.push(x.id);if(choice!=null){const ok=choice===x.c;record(x,ok,examState.times[x.id]||0);state.attempts++;state.bySubject[x.s]=state.bySubject[x.s]||{a:0,c:0};state.bySubject[x.s].a++;if(ok){state.correct++;state.bySubject[x.s].c++;if(state.weak[x.id]){state.weak[x.id]--;if(state.weak[x.id]<=0)delete state.weak[x.id]}}else state.weak[x.id]=(state.weak[x.id]||0)+1}});const elapsed=Math.round((now()-examState.start)/60000);v3.sessions.unshift({date:now(),mode:examState.year?'annale-'+examState.year:'mock',score:correct,total,wrong});v3.sessions=v3.sessions.slice(0,20);save();persist();$('mockRun').classList.add('hidden');$('mockResult').classList.remove('hidden');$('mockScore').textContent=`${correct}/56`;$('mockElapsed').textContent=`${elapsed} min · ${Object.keys(examState.answers).length} réponses`;$('mockBreakdown').innerHTML=SUBJECTS.map(s=>`<div class="scoreRow"><span>${s}</span><b>${by[s].c}/14</b></div>`).join('');$('reviewExamErrors').onclick=()=>{setTab('train');currentMode='exam-review';start([...new Set(wrong)],Math.min(wrong.length,20))};examState=null}
function bind(){if($('adaptiveStart'))$('adaptiveStart').onclick=()=>launchAdaptive(12,'adaptive');if($('trapMission'))$('trapMission').onclick=launchTraps;if($('minuteStart'))$('minuteStart').onclick=launchMinute;if($('startMock'))$('startMock').onclick=()=>startExam(null);if($('exam'))$('exam').onclick=()=>startExam(null);if($('mockPrev'))$('mockPrev').onclick=()=>navExam(-1);if($('mockNext'))$('mockNext').onclick=()=>navExam(1);if($('flagBtn'))$('flagBtn').onclick=()=>{if(!examState)return;const id=examState.items[examState.idx].x.id;examState.flags[id]=!examState.flags[id];renderExam()};if($('submitMock'))$('submitMock').onclick=()=>submitExam(false);if($('go'))$('go').onclick=()=>{currentMode='custom';start()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.v));}
bind();renderV3();augmentAnnales();setTab('today');
})();